

export const courseList = [
    "Master of Technology (M.Tech) in Mechanical Engineering",
    "Master of Technology (M.Tech) in Electrical Engineering",
    "Master of Technology (M.Tech) in Civil Engineering",
    "Master of Technology (M.Tech) in Computer Science",
    "Master of Technology (M.Tech) in Information Technology",
    "Master of Technology (M.Tech) in Aerospace Engineering",
    "Master of Technology (M.Tech) in Biotechnology",
    "Master of Technology (M.Tech) in Electronics and Communication Engineering",
    "Master of Technology (M.Tech) in Industrial Engineering",
    "Master of Technology (M.Tech) in Environmental Engineering",
    "Master of Technology (M.Tech) in Marine Engineering",
    "Master of Technology (M.Tech) in Agricultural Engineering",
    "Master of Technology (M.Tech) in Petroleum Engineering",
    "Master of Technology (M.Tech) in Mining Engineering",
    "Master of Technology (M.Tech) in Textile Engineering",
    "Master of Technology (M.Tech) in Metallurgical Engineering",
    "Master of Technology (M.Tech) in Nanotechnology",
    "Master of Science (M.Sc) in Mathematics",
    "Master of Science (M.Sc) in Physics",
    "Master of Science (M.Sc) in Chemistry",
    "Master of Science (M.Sc) in Biology",
    "Master of Science (M.Sc) in Statistics",
    "Master of Science (M.Sc) in Computer Science",
    "Master of Science (M.Sc) in Environmental Science",
    "Master of Science (M.Sc) in Geology",
    "Master of Science (M.Sc) in Biotechnology",
    "Master of Science (M.Sc) in Electronics",
    "Master of Science (M.Sc) in Communication",
    "Master of Science (M.Sc) in Information Technology",
    "Master of Arts (M.A) in English Literature",
    "Master of Arts (M.A) in History",
    "Master of Arts (M.A) in Economics",
    "Master of Arts (M.A) in Political Science",
    "Master of Arts (M.A) in Sociology",
    "Master of Arts (M.A) in Psychology",
    "Master of Arts (M.A) in Anthropology",
    "Master of Arts (M.A) in Linguistics",
    "Master of Arts (M.A) in Philosophy",
    "Master of Business Administration (MBA)",
    "Master of Business Administration (MBA) in Marketing",
    "Master of Business Administration (MBA) in Finance",
    "Master of Business Administration (MBA) in Human Resource Management",
    "Master of Business Administration (MBA) in Operations Management",
    "Master of Business Administration (MBA) in International Business",
    "Master of Business Administration (MBA) in Information Technology",
    "Master of Computer Applications (MCA)",
    "Master of Fine Arts (MFA) in Graphic Design",
    "Master of Fine Arts (MFA) in Painting",
    "Master of Fine Arts (MFA) in Sculpture",
    "Master of Fine Arts (MFA) in Photography",
    "Master of Fine Arts (MFA) in Film Making",
    "Master of Fine Arts (MFA) in Animation",
    "Master of Fine Arts (MFA) in Music",
    "Master of Fine Arts (MFA) in Dance",
    "Master of Fine Arts (MFA) in Theater",
    "Master of Fine Arts (MFA) in Creative Writing",
    "Master of Fine Arts (MFA) in Fashion Design",
    "Master of Laws (LL.M)",
    "Master of Laws (LL.M) in Business Law",
    "Master of Laws (LL.M) in Criminal Law",
    "Master of Laws (LL.M) in Intellectual Property Law",
    "Master of Laws (LL.M) in International Law",
    "Master of Laws (LL.M) in Tax Law",
    "Master of Laws (LL.M) in Environmental Law",
    "Master of Laws (LL.M) in Human Rights Law",
    "Bachelor of Technology (B.Tech) in Computer Science",
    "Bachelor of Technology (B.Tech) in Mechanical Engineering",
    "Bachelor of Technology (B.Tech) in Electrical Engineering",
    "Bachelor of Technology (B.Tech) in Civil Engineering",
    "Bachelor of Technology (B.Tech) in Chemical Engineering",
    "Bachelor of Technology (B.Tech) in Aerospace Engineering",
    "Bachelor of Technology (B.Tech) in Biotechnology",
    "Bachelor of Technology (B.Tech) in Information Technology",
    "Bachelor of Technology (B.Tech) in Electronics and Communication Engineering",
    "Bachelor of Technology (B.Tech) in Automobile Engineering",
    "Bachelor of Technology (B.Tech) in Industrial Engineering",
    "Bachelor of Technology (B.Tech) in Environmental Engineering",
    "Bachelor of Technology (B.Tech) in Marine Engineering",
    "Bachelor of Technology (B.Tech) in Agricultural Engineering",
    "Bachelor of Technology (B.Tech) in Petroleum Engineering",
    "Bachelor of Technology (B.Tech) in Mining Engineering",
    "Bachelor of Technology (B.Tech) in Textile Engineering",
    "Bachelor of Technology (B.Tech) in Metallurgical Engineering",
    "Bachelor of Technology (B.Tech) in Nanotechnology",
    "Bachelor of Science (B.Sc) in Mathematics",
    "Bachelor of Science (B.Sc) in Physics",
    "Bachelor of Science (B.Sc) in Chemistry",
    "Bachelor of Science (B.Sc) in Biology",
    "Bachelor of Science (B.Sc) in Statistics",
    "Bachelor of Science (B.Sc) in Computer Science",
    "Bachelor of Science (B.Sc) in Environmental Science",
    "Bachelor of Science (B.Sc) in Geology",
    "Bachelor of Arts (B.A) in English Literature",
    "Bachelor of Arts (B.A) in History",
    "Bachelor of Arts (B.A) in Economics",
    "Bachelor of Arts (B.A) in Political Science",
    "Bachelor of Arts (B.A) in Sociology",
    "Bachelor of Arts (B.A) in Psychology",
    "Bachelor of Engineering (B.E) in Electrical Engineering",
    "Bachelor of Engineering (B.E) in Mechanical Engineering",
    "Bachelor of Engineering (B.E) in Civil Engineering",
    "Bachelor of Engineering (B.E) in Chemical Engineering",
    "Bachelor of Engineering (B.E) in Aerospace Engineering",
    "Bachelor of Engineering (B.E) in Biotechnology",
    "Bachelor of Engineering (B.E) in Computer Engineering",
    "Bachelor of Engineering (B.E) in Electronics Engineering",
    "Bachelor of Commerce (B.Com) in Accounting",
    "Bachelor of Commerce (B.Com) in Finance",
    "Bachelor of Commerce (B.Com) in Banking and Insurance",
    "Bachelor of Commerce (B.Com) in Taxation",
    "Bachelor of Commerce (B.Com) in Marketing",
    "Bachelor of Commerce (B.Com) in Economics",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Business Administration (BBA) in Marketing",
    "Bachelor of Business Administration (BBA) in Finance",
    "Bachelor of Business Administration (BBA) in Human Resource Management",
    "Bachelor of Fine Arts (BFA) in Graphic Design",
    "Bachelor of Fine Arts (BFA) in Painting",
    "Bachelor of Fine Arts (BFA) in Sculpture",
    "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
    "Web Development Bootcamp",
    "Data Science Certification",
    "Digital Marketing Course",
    "Cybersecurity Training Program",
    "Graphic Design Workshop",
    "Project Management Certification",
    "Mobile App Development Course",
    "UI/UX Design Course",
    "Cloud Computing Certification",
    "Blockchain Fundamentals",
    "Artificial Intelligence Training",
    "Machine Learning Bootcamp",
    "Network Engineering Certification",
    "Social Media Marketing Workshop",
    "Content Writing Course",
    "Game Development Bootcamp",
    "Ethical Hacking Workshop",
    "Financial Modeling Certification",
    "Photography Masterclass",
    "Video Editing Course",
    "Music Production Workshop",
    "Interior Design Certification",
    "Language Proficiency Course (e.g., TOEFL, IELTS)",
    "Health and Fitness Certification",
    "Cooking and Culinary Arts Workshop",
    "Personal Finance Management Course",
    "Public Speaking Training",
    "Leadership Development Program",
    "Entrepreneurship Bootcamp",
    "Career Counseling Certification",
    "Life Coaching Workshop",
    "Yoga Teacher Training Program",
    "Mindfulness and Meditation Course",
    "Self-Defense Workshop",
    "Art and Craft Classes",
    "Foreign Language Learning Program",
    "Event Management Certification",
    "Fashion Design Workshop",
    "Travel and Tourism Course",
    "Environmental Sustainability Certification",
    "Green Building Workshop",
    "First Aid Training Program",
    "Emergency Response Certification",
    "Parenting and Childcare Course",
    "Pet Grooming Workshop",
    "Professional Makeup Artistry Course",
    "Film Acting Workshop",
    "Stress Management Certification",
    "Personal Development Seminar",
    "Mind Mapping Workshop",
    "Productivity Hacks Course",
    "Time Management Training",
    "Assertiveness Skills Workshop",
    "Emotional Intelligence Certification",
    "Conflict Resolution Course",
    "Negotiation Skills Workshop",
    "Critical Thinking Training",
    "Problem-Solving Seminar",
    "Decision-Making Workshop",
    "Creativity and Innovation Course",
    "Risk Management Certification",
    "Change Management Training",
    "Agile Methodologies Workshop",
    "Scrum Master Certification",
    "Lean Six Sigma Course",
    "Quality Management Seminar",
    "Supply Chain Management Training",
    "Inventory Management Certification",
    "Retail Sales Workshop",
    "Customer Service Excellence Course",
    "Business Communication Training",
    "Presentation Skills Workshop",
    "Negotiation and Persuasion Course",
    "Financial Literacy Seminar",
    "Investment Strategies Workshop",
    "Real Estate Investment Certification",
    "Stock Market Trading Course",
    "Forex Trading Seminar",
    "Cryptocurrency Trading Workshop",
    "Personal Branding Course",
    "Networking and Relationship Building Training",
    "Career Transition Workshop",
    "Job Interview Preparation Seminar",
    "Resume Writing Course",
    "LinkedIn Profile Optimization Training",
    "Freelancing Fundamentals Workshop",
    "Remote Work Productivity Course",
    "Digital Nomad Lifestyle Seminar",
    "Side Hustle Creation Workshop",
    "E-commerce Business Certification",
    "Social Entrepreneurship Training",
    "Nonprofit Management Seminar",
    "Fundraising Strategies Workshop",
    "Grant Writing Course",
    "Event Planning and Management Certification",
    "Wedding Planning Workshop",
    "Concert and Festival Production Seminar",
    "Film and TV Production Course",
    "Scriptwriting Workshop",
    "Acting for Camera Certification",
    "Voice Acting Seminar",
    "Animation and VFX Training",
    "3D Modeling Workshop",
    "Game Design and Development Course",
    "Augmented Reality Certification",
    "Virtual Reality Seminar",
    "Digital Painting Workshop",
    "Cartooning and Comic Art Course",
    "Illustration Techniques Seminar",
    "Calligraphy and Hand Lettering Workshop",
    "Typography and Font Design Course",
    "Bookbinding and Book Arts Seminar",
    "Jewelry Making Workshop",
    "Pottery and Ceramics Course",
    "Woodworking and Carpentry Seminar",
    "Metalworking and Blacksmithing Workshop",
    "Glassblowing and Glass Art Course",
    "Textile Design Seminar",
    "Fashion Illustration Workshop",
    "Pattern Making and Sewing Course",
    "Fashion Styling Seminar",
    "Fashion Retail Management Workshop",
    "Health and Wellness Coaching Certification",
    "Nutrition and Dietetics Course",
    "Fitness Training and Exercise Physiology Seminar",
    "Mind-Body Medicine Workshop",
    "Alternative Medicine Certification",
    "Holistic Healing Course",
    "Ayurveda and Yoga Therapy Seminar",
    "Traditional Chinese Medicine Workshop",
    "Acupuncture and Acupressure Course",
    "Reiki and Energy Healing Seminar",
    "Crystal Healing Workshop",
    "Herbalism and Aromatherapy Course",
    "Massage Therapy Seminar",
    "Spa and Wellness Management Workshop",
    "Mindful Eating Certification",
    "Cooking for Health and Wellness Course",
    "Plant-Based Nutrition Seminar",
    "Sports Nutrition Workshop",
    "Healthy Lifestyle Coaching Certification",
    "Mental Health Awareness Course",
    "Counseling Skills Seminar",
    "Positive Psychology Workshop",
    "Stress Reduction Techniques Course",
    "Anxiety and Depression Management Seminar",
    "Trauma-Informed Care Workshop",
    "Substance Abuse Counseling Certification",
    "Relationship Counseling Course",
    "Family Therapy Seminar",
    "Grief Counseling Workshop",
    "Art Therapy Certification",
    "Music Therapy Course",
    "Dance Movement Therapy Seminar",
    "Play Therapy Workshop",
    "Expressive Arts Therapy Certification",
    "Applied Behavior Analysis Course",
    "Special Education Needs Seminar",
    "Speech-Language Pathology Workshop",
    "Occupational Therapy Certification",
    "Physical Therapy Course",
    "Nursing and Healthcare Training",
    "Emergency Medical Services Seminar",
    "Paramedic and EMT Workshop",
    "Medical Assistant Certification",
    "Healthcare Administration Course",
    "Health Information Management Seminar",
    "Healthcare Ethics Workshop",
    "Health Policy and Advocacy Certification",
    "Public Health and Epidemiology Course",
    "Global Health Seminar",
    "Health Equity and Social Justice Workshop",
    "Environmental Health Certification",
    "Occupational Health and Safety Course",
    "Industrial Hygiene Seminar",
    "Infection Control Workshop",
    "Disaster Management Certification",
    "Emergency Preparedness Course",
    "Crisis Intervention Seminar",
    "Humanitarian Assistance Workshop",
    "Social Work and Welfare Certification",
    "Child and Family Services Course",
    "Gerontology and Aging Seminar",
    "Community Development Workshop",
    "International Development Certification",
    "Sustainable Development Course",
    "Urban Planning and Design Seminar",
    "Environmental Sustainability Workshop",
    "Renewable Energy Certification",
    "Climate Change Adaptation Course",
    "Biodiversity Conservation Seminar",
    "Ecotourism and Sustainable Travel Workshop",
    "Environmental Policy and Governance Certification",
    "Green Building and Architecture Course",
    "Environmental Education Seminar",
    "Conservation Biology Workshop",
    "Marine and Coastal Management Certification",
    "Forestry and Natural Resource Management Course",
    "Water Resource Management Seminar",
    "Soil Science and Land Management Workshop",
    "Agricultural Sustainability Certification",
    "Food Security and Nutrition Course",
    "Agroecology Seminar",
    "Organic Farming and Permaculture Workshop",
    "Urban Agriculture Certification",
    "Rural Development Course",
    "Community-based Natural Resource Management Seminar",
    "Gender and Development Workshop",
    "Disability Studies Certification",
    "Human Rights and Social Justice Course",
    "Peace and Conflict Studies Seminar",
    "International Relations Workshop",
    "Diplomacy and Negotiation Certification",
    "Security Studies Course",
    "Terrorism and Counterterrorism Seminar",
    "Foreign Policy Analysis Workshop",
    "Global Governance Certification",
    "Development Economics Course",
    "Financial Inclusion Seminar",
    "Microfinance and Microenterprise Workshop",
    "International Trade Certification",
    "Trade Policy and Negotiation Course",
    "Export Management Seminar",
    "Import-Export Documentation Workshop",
    "Logistics and Supply Chain Management Certification",
    "Inventory Control Course",
    "Warehouse Management Seminar",
    "Transportation and Distribution Workshop",
    "Retail Management Certification",
    "Merchandising and Inventory Planning Course",
    "Store Operations Seminar",
    "Visual Merchandising Workshop",
    "Sales and Marketing Certification",
    "Customer Relationship Management Course",
    "Sales Techniques Seminar",
    "Marketing Strategies Workshop",
    "Digital Marketing Certification",
    "Search Engine Optimization Course",
    "Social Media Marketing Seminar",
    "Content Marketing Workshop",
    "Email Marketing Certification",
    "Copywriting Course",
    "Public Relations Seminar",
    "Advertising and Branding Workshop",
    "Market Research Certification",
    "Data Analysis and Visualization Course",
    "Business Intelligence Seminar",
    "Data Mining Workshop",
    "Statistical Analysis Certification",
    "Predictive Analytics Course",
    "Machine Learning Seminar",
    "Deep Learning Workshop",
    "Natural Language Processing Certification",
    "Computer Vision Course",
    "Artificial Intelligence Seminar",
    "Robotics and Automation Workshop",
    "Quantum Computing Certification",
    "Blockchain Technology Course",
    "Cryptocurrency Seminar",
    "Smart Contracts Workshop",
    "Internet of Things (IoT) Certification",
    "Augmented Reality Course",
    "Virtual Reality Seminar",
    "Mixed Reality Workshop",
    "Gaming and Gamification Certification",
    "Game Design Course",
    "Game Development Seminar",
    "Game Programming Workshop",
    "Mobile App Development Certification",
    "Android Development Course",
    "iOS Development Seminar",
    "Cross-platform App Development Workshop",
    "Web Development Certification",
    "Frontend Development Course",
    "Backend Development Seminar",
    "Full Stack Development Workshop",
    "UI/UX Design Certification",
    "User Interface Design Course",
    "User Experience Seminar",
    "Graphic Design Workshop",
    "Logo Design Course",
    "Illustration Seminar",
    "Animation Workshop",
    "Film and Video Editing Certification",
    "Motion Graphics Course",
    "Visual Effects Seminar",
    "Sound Design Workshop",
    "Music Production Certification",
    "Electronic Music Course",
    "Songwriting Seminar",
    "Music Theory Workshop",
    "Photography Certification",
    "Digital Photography Course",
    "Portrait Photography Seminar",
    "Landscape Photography Workshop",
    "Street Photography Certification",
    "Fashion Photography Course",
    "Event Photography Seminar",
    "Food Photography Workshop",
    "Travel Photography Certification",
    "Nature and Wildlife Photography Course",
    "Documentary Photography Seminar",
    "Architecture and Interior Photography Workshop",
    "Night Photography Certification",
    "Product Photography Course",
    "Wedding Photography Seminar",
    "Fine Arts and Crafts Workshop",
    "Drawing and Painting Certification",
    "Watercolor and Gouache Course",
    "Oil and Acrylic Painting Seminar",
    "Charcoal and Pastel Drawing Workshop",
    "Printmaking Certification",
    "Woodcut and Linocut Course",
    "Etching and Engraving Seminar",
    "Screenprinting Workshop",
    "Sculpture and Ceramics Certification",
    "Clay Modeling and Pottery Course",
    "Stone and Metal Sculpture Seminar",
    "Woodcarving and Woodworking Workshop",
    "Glass Art Certification",
    "Stained Glass Course",
    "Glassblowing Seminar",
    "Fused Glass Workshop",
    "Textile and Fiber Arts Certification",
    "Weaving and Knitting Course",
    "Embroidery and Needlework Seminar",
    "Dyeing and Printing Workshop",
    "Quilting and Patchwork Certification",
    "Fashion Design Course",
    "Fashion Illustration Seminar",
    "Patternmaking and Draping Workshop",
    "Sewing and Garment Construction Certification",
    "Fashion Styling Course",
    "Accessory Design Seminar",
    "Footwear Design Workshop",
    "Textile Design Certification",
    "Print Design Course",
    "Surface Design Seminar",
    "Repeat Patterns Workshop",
    "Color Theory Certification",
    "Design Thinking Course",
    "User-Centered Design Seminar",
    "Prototyping and Testing Workshop",
    "Design Management Certification",
    "Product Design Course",
    "Industrial Design Seminar",
    "Sustainable Design Workshop",
    "Interior Design Certification",
    "Residential Design Course",
    "Commercial Design Seminar",
    "Hospitality Design Workshop",
    "Landscape Design Certification",
    "Urban Design Course",
    "Environmental Design Seminar",
    "Architectural Design Workshop",
    "Business Administration Certification",
    "Management Course",
    "Leadership Seminar",
    "Human Resources Workshop",
    "Finance and Accounting Certification",
    "Financial Planning Course",
    "Investment Management Seminar",
    "Marketing and Sales Workshop",
    "Customer Service Certification",
    "Service Excellence Course",
    "Customer Relationship Management Seminar",
    "Operations and Supply Chain Management Workshop",
    "Quality Management Certification",
    "Six Sigma Course",
    "Lean Management Seminar",
    "Project Management Workshop",
    "Agile and Scrum Certification",
    "Change Management Course",
    "Organizational Development Seminar",
    "Strategic Management Workshop",
    "Entrepreneurship Certification",
    "Startup Course",
    "Venture Capital Seminar",
    "Business Development Workshop",
    "Economics and Econometrics Certification",
    "Macroeconomics Course",
    "Microeconomics Seminar",
    "Development Economics Workshop",
    "International Economics Certification",
    "Trade Theory Course",
    "Monetary Policy Seminar",
    "Labor Economics Workshop",
    "Public Economics Certification",
    "Taxation Course",
    "Fiscal Policy Seminar",
    "Environmental Economics Workshop",
    "Health Economics Certification",
    "Education Economics Course",
    "Urban Economics Seminar",
    "Industrial Organization Workshop",
    "Energy Economics Certification",
    "Agricultural Economics Course",
    "Applied Economics Seminar",
    "Social Science Research Workshop",
    "Quantitative Methods Certification",
    "Statistical Analysis Course",
    "Survey Design Seminar",
    "Qualitative Research Workshop",
    "Data Collection and Analysis Certification",
    "Experimental Design Course",
    "Sampling Techniques Seminar",
    "Hypothesis Testing Workshop",
    "Research Ethics Certification",
    "Data Visualization Course",
    "Data Interpretation Seminar",
    "Reporting and Presentation Workshop",
    "Computer Science and Engineering Certification",
    "Software Development Course",
    "Database Management Seminar",
    "Network Security Workshop",
    "Information Technology Certification",
    "IT Service Management Course",
    "Cloud Computing Seminar",
    "Artificial Intelligence Workshop",
    "Machine Learning Certification",
    "Deep Learning Course",
    "Natural Language Processing Seminar",
    "Computer Vision Workshop",
    "Robotics and Automation Certification",
    "Embedded Systems Course",
    "IoT and Sensor Networks Seminar",
    "Cybersecurity Workshop",
    "Game Development Certification",
    "Virtual Reality Course",
    "Augmented Reality Seminar",
    "Digital Signal Processing Workshop",
    "Electronics and Communication Certification",
    "Microcontrollers and Microprocessors Course",
    "VLSI Design Seminar",
    "Wireless Communication Workshop",
    "Digital Image Processing Certification",
    "Biomedical Engineering Course",
    "Bioinformatics Seminar",
    "Nanotechnology Workshop",
    "Materials Science and Engineering Certification",
    "Civil Engineering Course",
    "Structural Engineering Seminar",
    "Transportation Engineering Workshop",
    "Geotechnical Engineering Certification",
    "Environmental Engineering Course",
    "Water Resources Engineering Seminar",
    "Construction Management Workshop",
    "Electrical Engineering Certification",
    "Power Systems Course",
    "Control Systems Seminar",
    "Renewable Energy Engineering Workshop",
    "Instrumentation and Measurement Certification",
    "Electromagnetics Course",
    "Signal Processing Seminar",
    "Robotics and Automation Workshop",
    "Mechanical Engineering Certification",
    "Thermodynamics Course",
    "Fluid Mechanics Seminar",
    "Heat Transfer Workshop",
    "Manufacturing Engineering Certification",
    "Industrial Engineering Course",
    "Operations Research Seminar",
    "Product Design Workshop",
    "Automotive Engineering Certification",
    "Aerospace Engineering Course",
    "Aeronautical Engineering Seminar",
    "Spacecraft Design Workshop",
    "Chemical Engineering Certification",
    "Process Engineering Course",
    "Polymer Science and Technology Seminar",
    "Environmental Engineering Workshop",
    "Biotechnology Certification",
    "Genetic Engineering Course",
    "Biochemical Engineering Seminar",
    "Bioinformatics Workshop",
    "Food Technology Certification",
    "Food Science Course",
    "Food Processing Seminar",
    "Food Packaging Workshop",
    "Pharmaceutical Science Certification",
    "Pharmacology Course",
    "Medicinal Chemistry Seminar",
    "Pharmaceutics Workshop",
    "Medical Science Certification",
    "Anatomy and Physiology Course",
    "Pathology Seminar",
    "Pharmacovigilance Workshop",
    "Healthcare Management Certification",
    "Hospital Administration Course",
    "Health Informatics Seminar",
    "Clinical Research Workshop",
    "Nursing and Midwifery Certification",
    "Nursing Practice Course",
    "Midwifery Seminar",
    "Geriatric Nursing Workshop",
    "Dental Science Certification",
    "Dentistry Course",
    "Orthodontics Seminar",
    "Endodontics Workshop",
    "Veterinary Science Certification",
    "Veterinary Medicine Course",
    "Veterinary Surgery Seminar",
    "Animal Nutrition Workshop",
    "Biomedical Science Certification",
    "Medical Laboratory Technology Course",
    "Biomedical Instrumentation Seminar",
    "Biomedical Imaging Workshop",
    "Psychology and Counseling Certification",
    "Counseling Psychology Course",
    "Clinical Psychology Seminar",
    "Psychological Testing Workshop",
    "Educational Psychology Certification",
    "School Counseling Course",
    "Child Psychology Seminar",
    "Developmental Psychology Workshop",
    "Social Work Certification",
    "Community Development Course",
    "Family Counseling Seminar",
    "Social Welfare Workshop",
    "Public Administration Certification",
    "Public Policy Course",
    "Government Administration Seminar",
    "Nonprofit Management Workshop",
    "International Relations Certification",
    "Global Governance Course",
    "Diplomacy Seminar",
    "Conflict Resolution Workshop",
    "Journalism and Mass Communication Certification",
    "Mass Media Course",
    "Broadcast Journalism Seminar",
    "Digital Media Workshop",
    "Creative Writing Certification",
    "Fiction Writing Course",
    "Poetry Seminar",
    "Screenwriting Workshop",
    "English Language and Literature Certification",
    "Literary Studies Course",
    "English Language Teaching Seminar",
    "Applied Linguistics Workshop",
    "History and Archaeology Certification",
    "Archival Studies Course",
    "Museum Studies Seminar",
    "Historical Research Workshop",
    "Sociology and Anthropology Certification",
    "Social Anthropology Course",
    "Cultural Studies Seminar",
    "Anthropological Research Workshop",
    "Philosophy and Ethics Certification",
    "Ethical Philosophy Course",
    "Metaethics Seminar",
    "Applied Ethics Workshop",
    "Religious Studies Certification",
    "Comparative Religion Course",
    "Theology Seminar",
    "Religious Education Workshop",
    "Arts and Humanities Certification",
    "Art History Course",
    "Philosophy of Art Seminar",
    "Aesthetics Workshop",
    "Musicology Certification",
    "Music History Course",
    "Music Theory Seminar",
    "Ethnomusicology Workshop",
    "Performing Arts Certification",
    "Theatre Studies Course",
    "Dance Seminar",
    "Acting Workshop",
    "Visual Arts Certification",
    "Fine Arts Course",
    "Drawing and Painting Seminar",
    "Sculpture Workshop",
    "Design and Applied Arts Certification",
    "Graphic Design Course",
    "Industrial Design Seminar",
    "Fashion Design Workshop",
    "Film and Television Certification",
    "Film Studies Course",
    "Television Production Seminar",
    "Screenwriting Workshop",
    "Communication and Media Studies Certification",
    "Media Studies Course",
    "Communication Theory Seminar",
    "Media Production Workshop",
    "Education and Teaching Certification",
    "Primary Education Course",
    "Secondary Education Seminar",
    "Higher Education Workshop",
    "Special Education Certification",
    "Inclusive Education Course",
    "Learning Disabilities Seminar",
    "Early Childhood Education Workshop",
    "Language and Linguistics Certification",
    "Linguistics Course",
    "Phonetics Seminar",
    "Sociolinguistics Workshop",
    "TESOL Certification",
    "TEFL Course",
    "TESL Seminar",
    "Educational Technology Workshop",
    "E-learning Certification",
    "Instructional Design Course",
    "Blended Learning Seminar",
    "Online Course Development Workshop",
    "Library and Information Science Certification",
    "Information Management Course",
    "Library Studies Seminar",
    "Archives Management Workshop",
    "Law and Legal Studies Certification",
    "Criminal Law Course",
    "Civil Law Seminar",
    "International Law Workshop",
    "Human Rights Certification",
    "Labour Law Course",
    "Environmental Law Seminar",
    "Intellectual Property Workshop",
    "Business Law Certification",
    "Corporate Law Course",
    "Tax Law Seminar",
    "Banking and Finance Law Workshop",
    "Health Law Certification",
    "Medicine and Law Course",
    "Bioethics Seminar",
    "Regulatory Compliance Workshop",
    "Environmental Law Certification",
    "Energy Law Course",
    "Climate Law Seminar",
    "International Environmental Law Workshop",
    "Public International Law Certification",
    "Diplomatic Law Course",
    "Law of Armed Conflict Seminar",
    "International Humanitarian Law Workshop",
    "Sports Law Certification",
    "Athlete Representation Course",
    "Anti-doping Seminar",
    "Broadcasting Rights Workshop",
    "Entertainment Law Certification",
    "Music Law Course",
    "Film and Television Seminar",
    "Intellectual Property Workshop",
    "Technology Law Certification",
    "Cybersecurity Law Course",
    "Data Protection Seminar",
    "E-commerce Regulation Workshop",
    "Maritime Law Certification",
    "Admiralty Law Course",
    "Marine Insurance Seminar",
    "Ship Finance Workshop",
    "Air and Space Law Certification",
    "Aviation Law Course",
];