export const technologyStack = [
    "Android", "Angular", "ASP.NET", "AWS", "Bootstrap", "C#", "C++", "CSS", "Django", "Docker",
    "Express.js", "Flask", "Git", "Heroku", "HTML", "Java", "JavaScript", "Kubernetes", "Linux",
    "MongoDB", "MySQL", "Nginx", "Node.js", "PHP", "PostgreSQL", "Python", "React", "Redis",
    "Ruby on Rails", "SQLite", "Spring Boot", "Swift", "Tailwind CSS", "TensorFlow", "TypeScript",
    "Unity", "Vue.js", "Scala", "Elixir", "Rust", "Kotlin", "SwiftUI", "Firebase", "AWS Lambda",
    "GraphQL", "REST API", "SOAP", "OAuth", "JWT", "CI/CD", "Jenkins", "Ansible", "Terraform",
    "RabbitMQ", "Kafka", "Elasticsearch", "Prometheus", "Grafana", "Zabbix", "Nagios", "Splunk",
    "Azure", "Google Cloud Platform", "Serverless", "Microservices", "Monolithic", "Lambda Architecture",
    "Server-side Rendering", "Client-side Rendering", "Progressive Web Apps", "Single Page Applications",
    "Micro-frontends", "Event-driven Architecture", "Domain-driven Design", "Clean Architecture",
    "Model View Controller (MVC)", "Model View ViewModel (MVVM)", "Model View Presenter (MVP)",
    "Model View Intent (MVI)", "Observer Pattern", "Singleton Pattern", "Factory Pattern",
    "Builder Pattern", "Adapter Pattern", "Decorator Pattern", "Strategy Pattern", "Facade Pattern",
    "Command Pattern", "Prototype Pattern", "Proxy Pattern", "Composite Pattern", "Iterator Pattern",
    "State Pattern", "Visitor Pattern", "Chain of Responsibility Pattern", "Flyweight Pattern",
    "Mediator Pattern", "Memento Pattern", "Template Method Pattern", "Bridge Pattern",
    "Interpreter Pattern", "Abstract Factory Pattern", "Observer Pattern", "Service-oriented Architecture",
    "Resource-oriented Architecture", "Representational State Transfer (REST)", "GraphQL", "SOAP",
    "Simple Object Access Protocol (SOAP)", "WebSocket", "WebRTC", "Internet Protocol (IP)",
    "Transmission Control Protocol (TCP)", "User Datagram Protocol (UDP)", "Domain Name System (DNS)",
    "Dynamic Host Configuration Protocol (DHCP)", "File Transfer Protocol (FTP)", "Secure Shell (SSH)",
    "Simple Mail Transfer Protocol (SMTP)", "Post Office Protocol (POP)", "Internet Message Access Protocol (IMAP)",
    "LDAP (Lightweight Directory Access Protocol)", "Network File System (NFS)", "Common Internet File System (CIFS)",
    "Border Gateway Protocol (BGP)", "Open Shortest Path First (OSPF)", "Virtual Private Network (VPN)"
];
